"""
PLY File Export Module

Exports 3D point clouds to PLY format (Polygon File Format / Stanford Triangle Format)
Supports both ASCII and binary formats with vertex positions, colors, and metadata.
"""

import numpy as np
from pathlib import Path
from typing import Optional, Dict
from datetime import datetime
from ..geometry.two_view import CameraPose
from ..utils.logger import logger


class PLYExporter:
    """
    Exports 3D point clouds to PLY format

    Supports ASCII and binary formats with RGB colors and optional metadata.
    """

    @staticmethod
    def export_point_cloud(
        file_path: str,
        points_3d: np.ndarray,
        colors: Optional[np.ndarray] = None,
        normals: Optional[np.ndarray] = None,
        binary: bool = True,
        metadata: Optional[Dict] = None
    ) -> None:
        """
        Export point cloud to PLY file

        Args:
            file_path: Output PLY file path
            points_3d: Nx3 array of 3D coordinates
            colors: Optional Nx3 RGB colors (0-255)
            normals: Optional Nx3 surface normals
            binary: If True, write binary format; otherwise ASCII
            metadata: Optional dict with reconstruction metadata
        """
        file_path = Path(file_path)
        file_path.parent.mkdir(parents=True, exist_ok=True)

        n_points = len(points_3d)

        # Validate inputs
        if colors is not None:
            assert len(colors) == n_points, "Colors must match number of points"
            colors = colors.astype(np.uint8)
        else:
            colors = np.full((n_points, 3), 128, dtype=np.uint8)  # Gray

        if normals is not None:
            assert len(normals) == n_points, "Normals must match number of points"

        logger.info(f"Exporting {n_points} points to {file_path} ({'binary' if binary else 'ASCII'})")

        if binary:
            PLYExporter._write_binary(file_path, points_3d, colors, normals, metadata)
        else:
            PLYExporter._write_ascii(file_path, points_3d, colors, normals, metadata)

        logger.info(f"Successfully exported point cloud to {file_path}")

    @staticmethod
    def _write_header(
        f,
        n_points: int,
        has_colors: bool,
        has_normals: bool,
        binary: bool,
        metadata: Optional[Dict] = None
    ) -> None:
        """Write PLY header"""
        f.write(b"ply\n" if binary else "ply\n")

        # Format
        if binary:
            f.write(b"format binary_little_endian 1.0\n")
        else:
            f.write("format ascii 1.0\n")

        # Metadata comments
        f.write((b"comment Generated by Multi-View 3D Reconstruction Pipeline\n" if binary
                else "comment Generated by Multi-View 3D Reconstruction Pipeline\n"))

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        f.write((f"comment Created: {timestamp}\n".encode() if binary
                else f"comment Created: {timestamp}\n"))

        if metadata:
            if 'n_cameras' in metadata:
                f.write((f"comment Number of cameras: {metadata['n_cameras']}\n".encode() if binary
                        else f"comment Number of cameras: {metadata['n_cameras']}\n"))
            if 'reprojection_error' in metadata:
                f.write((f"comment Mean reprojection error: {metadata['reprojection_error']:.3f} pixels\n".encode() if binary
                        else f"comment Mean reprojection error: {metadata['reprojection_error']:.3f} pixels\n"))
            if 'reconstruction_type' in metadata:
                f.write((f"comment Reconstruction type: {metadata['reconstruction_type']}\n".encode() if binary
                        else f"comment Reconstruction type: {metadata['reconstruction_type']}\n"))

        # Vertex properties
        f.write((f"element vertex {n_points}\n".encode() if binary
                else f"element vertex {n_points}\n"))

        f.write((b"property float x\n" if binary else "property float x\n"))
        f.write((b"property float y\n" if binary else "property float y\n"))
        f.write((b"property float z\n" if binary else "property float z\n"))

        if has_normals:
            f.write((b"property float nx\n" if binary else "property float nx\n"))
            f.write((b"property float ny\n" if binary else "property float ny\n"))
            f.write((b"property float nz\n" if binary else "property float nz\n"))

        if has_colors:
            f.write((b"property uchar red\n" if binary else "property uchar red\n"))
            f.write((b"property uchar green\n" if binary else "property uchar green\n"))
            f.write((b"property uchar blue\n" if binary else "property uchar blue\n"))

        f.write((b"end_header\n" if binary else "end_header\n"))

    @staticmethod
    def _write_ascii(
        file_path: Path,
        points_3d: np.ndarray,
        colors: np.ndarray,
        normals: Optional[np.ndarray],
        metadata: Optional[Dict]
    ) -> None:
        """Write PLY file in ASCII format"""
        with open(file_path, 'w') as f:
            # Write header
            PLYExporter._write_header(
                f, len(points_3d),
                has_colors=True,
                has_normals=(normals is not None),
                binary=False,
                metadata=metadata
            )

            # Write vertex data
            for i in range(len(points_3d)):
                x, y, z = points_3d[i]
                r, g, b = colors[i]

                if normals is not None:
                    nx, ny, nz = normals[i]
                    f.write(f"{x:.6f} {y:.6f} {z:.6f} {nx:.6f} {ny:.6f} {nz:.6f} {r} {g} {b}\n")
                else:
                    f.write(f"{x:.6f} {y:.6f} {z:.6f} {r} {g} {b}\n")

    @staticmethod
    def _write_binary(
        file_path: Path,
        points_3d: np.ndarray,
        colors: np.ndarray,
        normals: Optional[np.ndarray],
        metadata: Optional[Dict]
    ) -> None:
        """Write PLY file in binary format"""
        with open(file_path, 'wb') as f:
            # Write header
            PLYExporter._write_header(
                f, len(points_3d),
                has_colors=True,
                has_normals=(normals is not None),
                binary=True,
                metadata=metadata
            )

            # Prepare vertex data array
            if normals is not None:
                # dtype: x, y, z, nx, ny, nz, r, g, b
                dtype = np.dtype([
                    ('x', 'f4'), ('y', 'f4'), ('z', 'f4'),
                    ('nx', 'f4'), ('ny', 'f4'), ('nz', 'f4'),
                    ('red', 'u1'), ('green', 'u1'), ('blue', 'u1')
                ])
                vertices = np.empty(len(points_3d), dtype=dtype)
                vertices['x'] = points_3d[:, 0]
                vertices['y'] = points_3d[:, 1]
                vertices['z'] = points_3d[:, 2]
                vertices['nx'] = normals[:, 0]
                vertices['ny'] = normals[:, 1]
                vertices['nz'] = normals[:, 2]
                vertices['red'] = colors[:, 0]
                vertices['green'] = colors[:, 1]
                vertices['blue'] = colors[:, 2]
            else:
                # dtype: x, y, z, r, g, b
                dtype = np.dtype([
                    ('x', 'f4'), ('y', 'f4'), ('z', 'f4'),
                    ('red', 'u1'), ('green', 'u1'), ('blue', 'u1')
                ])
                vertices = np.empty(len(points_3d), dtype=dtype)
                vertices['x'] = points_3d[:, 0]
                vertices['y'] = points_3d[:, 1]
                vertices['z'] = points_3d[:, 2]
                vertices['red'] = colors[:, 0]
                vertices['green'] = colors[:, 1]
                vertices['blue'] = colors[:, 2]

            # Write binary data
            vertices.tofile(f)

    @staticmethod
    def export_cameras(
        file_path: str,
        camera_poses: Dict[int, CameraPose],
        K: np.ndarray,
        scale: float = 0.1
    ) -> None:
        """
        Export camera frustums as PLY file for visualization

        Args:
            file_path: Output PLY file path
            camera_poses: Dict mapping img_idx -> CameraPose
            K: Camera intrinsic matrix
            scale: Scale factor for frustum size
        """
        file_path = Path(file_path)
        file_path.parent.mkdir(parents=True, exist_ok=True)

        vertices = []
        colors = []

        # Generate color for each camera
        n_cameras = len(camera_poses)
        camera_colors = np.array([
            [255, 0, 0],    # Red
            [0, 255, 0],    # Green
            [0, 0, 255],    # Blue
            [255, 255, 0],  # Yellow
            [255, 0, 255],  # Magenta
            [0, 255, 255],  # Cyan
        ])

        for cam_idx, (img_idx, pose) in enumerate(sorted(camera_poses.items())):
            # Camera center
            C = -pose.R.T @ pose.t

            # Frustum corners in image space
            h, w = 480, 640  # Assume standard image size
            corners_2d = np.array([
                [0, 0], [w, 0], [w, h], [0, h]
            ], dtype=np.float32)

            # Backproject to 3D at distance 'scale'
            corners_hom = np.hstack([corners_2d, np.ones((4, 1))])
            K_inv = np.linalg.inv(K)
            rays = (K_inv @ corners_hom.T).T
            corners_cam = rays * scale

            # Transform to world
            corners_world = (pose.R.T @ corners_cam.T).T + C

            # Add camera center
            vertices.append(C)
            color = camera_colors[cam_idx % len(camera_colors)]
            colors.append(color)

            # Add frustum corners
            for corner in corners_world:
                vertices.append(corner)
                colors.append(color)

        vertices = np.array(vertices)
        colors = np.array(colors, dtype=np.uint8)

        PLYExporter.export_point_cloud(
            file_path, vertices, colors,
            metadata={'reconstruction_type': 'Camera Frustums', 'n_cameras': n_cameras}
        )

        logger.info(f"Exported {n_cameras} camera frustums to {file_path}")


def export_reconstruction_to_ply(
    output_dir: str,
    points_3d: np.ndarray,
    colors: np.ndarray,
    camera_poses: Dict[int, CameraPose],
    K: np.ndarray,
    metadata: Optional[Dict] = None,
    prefix: str = "reconstruction"
) -> None:
    """
    Export complete reconstruction to PLY files

    Creates separate files for point cloud and camera frustums.

    Args:
        output_dir: Output directory
        points_3d: Nx3 3D points
        colors: Nx3 RGB colors
        camera_poses: Dict of camera poses
        K: Intrinsic matrix
        metadata: Optional metadata dict
        prefix: Filename prefix
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Export point cloud
    cloud_path = output_dir / f"{prefix}_points.ply"
    PLYExporter.export_point_cloud(
        str(cloud_path),
        points_3d,
        colors,
        binary=True,
        metadata=metadata
    )

    # Export cameras
    cameras_path = output_dir / f"{prefix}_cameras.ply"
    PLYExporter.export_cameras(
        str(cameras_path),
        camera_poses,
        K
    )

    logger.info(f"Exported reconstruction to {output_dir}:")
    logger.info(f"  - Point cloud: {cloud_path.name}")
    logger.info(f"  - Cameras: {cameras_path.name}")